// Auto-generated from business-english-500.md by build-data.py — do not edit by hand.
const CATEGORIES = [
  {
    "id": 1,
    "title": "会議・議論",
    "count": 45
  },
  {
    "id": 2,
    "title": "連絡・伝達",
    "count": 45
  },
  {
    "id": 3,
    "title": "日程・進行管理",
    "count": 35
  },
  {
    "id": 4,
    "title": "組織・人事",
    "count": 45
  },
  {
    "id": 5,
    "title": "営業・顧客",
    "count": 50
  },
  {
    "id": 6,
    "title": "財務・数字",
    "count": 50
  },
  {
    "id": 7,
    "title": "プロジェクト・業務推進",
    "count": 50
  },
  {
    "id": 8,
    "title": "製品・技術・IT",
    "count": 50
  },
  {
    "id": 9,
    "title": "取引・契約・調達物流",
    "count": 45
  },
  {
    "id": 10,
    "title": "ビジネス動詞",
    "count": 50
  },
  {
    "id": 11,
    "title": "形容詞・副詞・文をつなぐ表現",
    "count": 35
  }
];

const WORDS = [
  {"n": 1, "en": "agenda", "ja": "議題", "ex": "Please send me the agenda.", "exJa": "議題を送ってください", "cat": 1},
  {"n": 2, "en": "minutes", "ja": "議事録", "ex": "I'll take the minutes today.", "exJa": "今日は私が議事録を取ります", "cat": 1},
  {"n": 3, "en": "attendee", "ja": "出席者", "ex": "We have ten attendees.", "exJa": "出席者は10名です", "cat": 1},
  {"n": 4, "en": "facilitator", "ja": "進行役", "ex": "She is the facilitator today.", "exJa": "今日の進行役は彼女です", "cat": 1},
  {"n": 5, "en": "chair", "ja": "議長を務める", "ex": "He will chair the meeting.", "exJa": "彼が会議を仕切ります", "cat": 1},
  {"n": 6, "en": "briefing", "ja": "要点説明", "ex": "Let's start with a short briefing.", "exJa": "簡単な説明から始めましょう", "cat": 1},
  {"n": 7, "en": "debrief", "ja": "事後に報告する", "ex": "Let's debrief after the visit.", "exJa": "訪問後に振り返りましょう", "cat": 1},
  {"n": 8, "en": "workshop", "ja": "討議形式の会", "ex": "We held a workshop last week.", "exJa": "先週ワークショップを開きました", "cat": 1},
  {"n": 9, "en": "session", "ja": "回、時間枠", "ex": "The next session starts at two.", "exJa": "次の回は2時開始です", "cat": 1},
  {"n": 10, "en": "stand-up", "ja": "短時間の進捗共有", "ex": "We have a stand-up every morning.", "exJa": "毎朝、短い進捗会議があります", "cat": 1},
  {"n": 11, "en": "one-on-one", "ja": "1対1の面談", "ex": "I have a one-on-one with my manager.", "exJa": "上司と面談があります", "cat": 1},
  {"n": 12, "en": "kickoff", "ja": "立ち上げ会議", "ex": "The kickoff is next Monday.", "exJa": "キックオフは来週月曜です", "cat": 1},
  {"n": 13, "en": "recap", "ja": "要点をおさらいする", "ex": "Let me recap the main points.", "exJa": "要点をおさらいします", "cat": 1},
  {"n": 14, "en": "takeaway", "ja": "持ち帰るべき要点", "ex": "The key takeaway is cost.", "exJa": "重要な点はコストです", "cat": 1},
  {"n": 15, "en": "action item", "ja": "次にやるべき事項", "ex": "Please check your action items.", "exJa": "担当事項を確認してください", "cat": 1},
  {"n": 16, "en": "follow-up", "ja": "追跡対応", "ex": "I'll send a follow-up tomorrow.", "exJa": "明日フォローの連絡をします", "cat": 1},
  {"n": 17, "en": "align", "ja": "認識をすり合わせる", "ex": "Let's align on the schedule.", "exJa": "日程の認識を合わせましょう", "cat": 1},
  {"n": 18, "en": "alignment", "ja": "認識合わせ", "ex": "We need alignment with sales.", "exJa": "営業との認識合わせが必要です", "cat": 1},
  {"n": 19, "en": "consensus", "ja": "総意、合意", "ex": "We reached a consensus.", "exJa": "合意に達しました", "cat": 1},
  {"n": 20, "en": "objection", "ja": "異議", "ex": "Are there any objections?", "exJa": "異議はありますか", "cat": 1},
  {"n": 21, "en": "concern", "ja": "懸念", "ex": "I have one concern.", "exJa": "一つ懸念があります", "cat": 1},
  {"n": 22, "en": "clarify", "ja": "はっきりさせる", "ex": "Could you clarify this point?", "exJa": "この点を明確にしてもらえますか", "cat": 1},
  {"n": 23, "en": "clarification", "ja": "明確化、確認", "ex": "Thank you for the clarification.", "exJa": "ご説明ありがとうございます", "cat": 1},
  {"n": 24, "en": "elaborate", "ja": "詳しく述べる", "ex": "Could you elaborate on that?", "exJa": "もう少し詳しく教えてください", "cat": 1},
  {"n": 25, "en": "outline", "ja": "概要を述べる", "ex": "Let me outline the plan.", "exJa": "計画の概要を説明します", "cat": 1},
  {"n": 26, "en": "highlight", "ja": "際立たせる", "ex": "I'd like to highlight two risks.", "exJa": "2つのリスクを強調したいです", "cat": 1},
  {"n": 27, "en": "emphasize", "ja": "強調する", "ex": "He emphasized the deadline.", "exJa": "彼は締切を強調しました", "cat": 1},
  {"n": 28, "en": "raise", "ja": "論点を提起する", "ex": "She raised a good point.", "exJa": "彼女は良い論点を出しました", "cat": 1},
  {"n": 29, "en": "address", "ja": "取り上げる、対処する", "ex": "We must address this issue.", "exJa": "この課題に対処すべきです", "cat": 1},
  {"n": 30, "en": "acknowledge", "ja": "認める、受け止める", "ex": "I acknowledge the delay.", "exJa": "遅れがあることは認めます", "cat": 1},
  {"n": 31, "en": "confirm", "ja": "確認して確定する", "ex": "Please confirm the date.", "exJa": "日付を確定してください", "cat": 1},
  {"n": 32, "en": "conclude", "ja": "結論づける", "ex": "Let's conclude the discussion.", "exJa": "議論を締めましょう", "cat": 1},
  {"n": 33, "en": "conclusion", "ja": "結論", "ex": "What is your conclusion?", "exJa": "結論はどうなりますか", "cat": 1},
  {"n": 34, "en": "discussion point", "ja": "論点", "ex": "I have three discussion points.", "exJa": "論点が3つあります", "cat": 1},
  {"n": 35, "en": "attendance", "ja": "出席状況", "ex": "Attendance was low today.", "exJa": "今日は出席者が少なかったです", "cat": 1},
  {"n": 36, "en": "participant", "ja": "参加者", "ex": "Each participant gets a copy.", "exJa": "参加者全員に資料を配ります", "cat": 1},
  {"n": 37, "en": "host", "ja": "主催する", "ex": "Our team will host the meeting.", "exJa": "我々のチームが主催します", "cat": 1},
  {"n": 38, "en": "mute", "ja": "ミュートする", "ex": "Please mute your microphone.", "exJa": "マイクをミュートしてください", "cat": 1},
  {"n": 39, "en": "screen share", "ja": "画面共有", "ex": "Let me start the screen share.", "exJa": "画面共有を始めます", "cat": 1},
  {"n": 40, "en": "handout", "ja": "配布資料", "ex": "The handout is on the table.", "exJa": "配布資料は机の上です", "cat": 1},
  {"n": 41, "en": "deck", "ja": "スライド資料一式", "ex": "I'll update the deck tonight.", "exJa": "今夜スライドを更新します", "cat": 1},
  {"n": 42, "en": "presentation", "ja": "プレゼン", "ex": "Your presentation was clear.", "exJa": "プレゼンは分かりやすかったです", "cat": 1},
  {"n": 43, "en": "summarize", "ja": "要約する", "ex": "Let me summarize the results.", "exJa": "結果をまとめます", "cat": 1},
  {"n": 44, "en": "wrap up", "ja": "締めくくる", "ex": "Let's wrap up in five minutes.", "exJa": "あと5分で締めましょう", "cat": 1},
  {"n": 45, "en": "postpone", "ja": "延期する", "ex": "We postponed the review.", "exJa": "レビューを延期しました", "cat": 1},
  {"n": 46, "en": "recipient", "ja": "受け取る側の相手", "ex": "The recipient has not replied.", "exJa": "相手からまだ返事がありません", "cat": 2},
  {"n": 47, "en": "correspondence", "ja": "一連のやり取り", "ex": "I kept all the correspondence.", "exJa": "やり取りは全部保管しています", "cat": 2},
  {"n": 48, "en": "reach out", "ja": "こちらから連絡を取る", "ex": "I'll reach out to the client.", "exJa": "顧客に連絡を取ります", "cat": 2},
  {"n": 49, "en": "forward", "ja": "別の人に回す", "ex": "Please forward this to Tanaka.", "exJa": "これを田中さんに回してください", "cat": 2},
  {"n": 50, "en": "convey", "ja": "意図を伝える", "ex": "Please convey my thanks.", "exJa": "感謝をお伝えください", "cat": 2},
  {"n": 51, "en": "draft", "ja": "草案／下書きする", "ex": "I drafted a short proposal.", "exJa": "簡単な提案書を書きました", "cat": 2},
  {"n": 52, "en": "wording", "ja": "言い回し、文言", "ex": "Let's change the wording here.", "exJa": "ここの言い回しを変えましょう", "cat": 2},
  {"n": 53, "en": "tone", "ja": "言い方の調子", "ex": "The tone sounds too strong.", "exJa": "言い方が強すぎるようです", "cat": 2},
  {"n": 54, "en": "rephrase", "ja": "言い換える", "ex": "Could you rephrase that?", "exJa": "言い換えてもらえますか", "cat": 2},
  {"n": 55, "en": "context", "ja": "背景、前後の事情", "ex": "Give me some context first.", "exJa": "まず背景を教えてください", "cat": 2},
  {"n": 56, "en": "loop in", "ja": "情報共有の輪に入れる", "ex": "Please loop in the support team.", "exJa": "サポートも共有に入れてください", "cat": 2},
  {"n": 57, "en": "in the loop", "ja": "情報を共有された状態で", "ex": "Keep me in the loop.", "exJa": "私にも共有し続けてください", "cat": 2},
  {"n": 58, "en": "heads-up", "ja": "事前の一報", "ex": "Thanks for the heads-up.", "exJa": "事前に教えてくれて助かります", "cat": 2},
  {"n": 59, "en": "notify", "ja": "正式に知らせる", "ex": "We will notify all users.", "exJa": "全利用者に通知します", "cat": 2},
  {"n": 60, "en": "notification", "ja": "通知", "ex": "I received a notification.", "exJa": "通知を受け取りました", "cat": 2},
  {"n": 61, "en": "announce", "ja": "公に知らせる", "ex": "They announced a new product.", "exJa": "新製品を発表しました", "cat": 2},
  {"n": 62, "en": "announcement", "ja": "告知", "ex": "There is an announcement today.", "exJa": "今日、告知があります", "cat": 2},
  {"n": 63, "en": "circulate", "ja": "回覧する", "ex": "I'll circulate the report.", "exJa": "報告書を回覧します", "cat": 2},
  {"n": 64, "en": "distribute", "ja": "配布する", "ex": "Please distribute the samples.", "exJa": "サンプルを配布してください", "cat": 2},
  {"n": 65, "en": "inquiry", "ja": "問い合わせ", "ex": "We got an inquiry from Osaka.", "exJa": "大阪から問い合わせがありました", "cat": 2},
  {"n": 66, "en": "inquire", "ja": "問い合わせる", "ex": "I'll inquire about the price.", "exJa": "価格を問い合わせます", "cat": 2},
  {"n": 67, "en": "request", "ja": "依頼する／依頼", "ex": "Your request is approved.", "exJa": "ご依頼は承認されました", "cat": 2},
  {"n": 68, "en": "remind", "ja": "念のため伝える", "ex": "Please remind him tomorrow.", "exJa": "明日、彼に念押ししてください", "cat": 2},
  {"n": 69, "en": "reminder", "ja": "催促、リマインド", "ex": "I sent a reminder yesterday.", "exJa": "昨日リマインドしました", "cat": 2},
  {"n": 70, "en": "apologize", "ja": "謝罪する", "ex": "I apologize for the delay.", "exJa": "遅れをお詫びします", "cat": 2},
  {"n": 71, "en": "apology", "ja": "お詫び", "ex": "Please accept our apology.", "exJa": "お詫び申し上げます", "cat": 2},
  {"n": 72, "en": "appreciate", "ja": "ありがたく思う", "ex": "I appreciate your support.", "exJa": "ご支援に感謝します", "cat": 2},
  {"n": 73, "en": "get back to", "ja": "後ほど改めて連絡する", "ex": "I'll get back to you today.", "exJa": "本日中に折り返します", "cat": 2},
  {"n": 74, "en": "keep posted", "ja": "随時状況を知らせる", "ex": "I'll keep you posted.", "exJa": "進捗は随時お知らせします", "cat": 2},
  {"n": 75, "en": "bullet point", "ja": "箇条書き", "ex": "Use bullet points, not paragraphs.", "exJa": "段落でなく箇条書きにしてください", "cat": 2},
  {"n": 76, "en": "on behalf of", "ja": "〜を代表して", "ex": "I'm speaking on behalf of my team.", "exJa": "チームを代表して話します", "cat": 2},
  {"n": 77, "en": "as discussed", "ja": "先に話した通り", "ex": "As discussed, we will delay it.", "exJa": "話した通り、延期します", "cat": 2},
  {"n": 78, "en": "as per", "ja": "〜に従って", "ex": "As per the contract, we must pay.", "exJa": "契約に従い支払う必要があります", "cat": 2},
  {"n": 79, "en": "proofread", "ja": "誤りがないか読み返す", "ex": "Please proofread this page.", "exJa": "このページを読み返してください", "cat": 2},
  {"n": 80, "en": "look forward to", "ja": "〜を心待ちにする", "ex": "I look forward to your visit.", "exJa": "ご訪問を楽しみにしています", "cat": 2},
  {"n": 81, "en": "courtesy", "ja": "礼儀、厚意", "ex": "It's a courtesy call.", "exJa": "表敬の訪問です", "cat": 2},
  {"n": 82, "en": "prompt", "ja": "迅速な", "ex": "Thank you for your prompt reply.", "exJa": "迅速なご返答ありがとうございます", "cat": 2},
  {"n": 83, "en": "pending", "ja": "保留中の、未処理の", "ex": "The decision is still pending.", "exJa": "判断はまだ保留です", "cat": 2},
  {"n": 84, "en": "urgent", "ja": "急ぎの", "ex": "This is an urgent matter.", "exJa": "これは急ぎの案件です", "cat": 2},
  {"n": 85, "en": "confidential", "ja": "機密の", "ex": "This data is confidential.", "exJa": "このデータは機密です", "cat": 2},
  {"n": 86, "en": "internal", "ja": "社内の", "ex": "It's for internal use only.", "exJa": "社内限りです", "cat": 2},
  {"n": 87, "en": "external", "ja": "社外の", "ex": "We need an external review.", "exJa": "社外の確認が必要です", "cat": 2},
  {"n": 88, "en": "verbal", "ja": "口頭の", "ex": "We only have a verbal agreement.", "exJa": "口頭の合意しかありません", "cat": 2},
  {"n": 89, "en": "in writing", "ja": "書面で", "ex": "Please confirm it in writing.", "exJa": "書面でご確認ください", "cat": 2},
  {"n": 90, "en": "misunderstanding", "ja": "行き違い、誤解", "ex": "There was a misunderstanding.", "exJa": "行き違いがありました", "cat": 2},
  {"n": 91, "en": "schedule", "ja": "予定を組む／日程", "ex": "Let's schedule a call.", "exJa": "打ち合わせを設定しましょう", "cat": 3},
  {"n": 92, "en": "reschedule", "ja": "日程を組み直す", "ex": "Can we reschedule to Friday?", "exJa": "金曜に変更できますか", "cat": 3},
  {"n": 93, "en": "deadline", "ja": "締切", "ex": "The deadline is next Friday.", "exJa": "締切は来週金曜です", "cat": 3},
  {"n": 94, "en": "due date", "ja": "期日", "ex": "The due date has passed.", "exJa": "期日を過ぎました", "cat": 3},
  {"n": 95, "en": "timeline", "ja": "工程、時間軸", "ex": "Here is the project timeline.", "exJa": "これが工程表です", "cat": 3},
  {"n": 96, "en": "milestone", "ja": "節目", "ex": "We reached the first milestone.", "exJa": "最初の節目に到達しました", "cat": 3},
  {"n": 97, "en": "duration", "ja": "所要期間", "ex": "The duration is three months.", "exJa": "期間は3か月です", "cat": 3},
  {"n": 98, "en": "interval", "ja": "間隔", "ex": "Check it at one-hour intervals.", "exJa": "1時間間隔で確認してください", "cat": 3},
  {"n": 99, "en": "quarter", "ja": "四半期", "ex": "Sales grew this quarter.", "exJa": "今四半期は売上が伸びました", "cat": 3},
  {"n": 100, "en": "fiscal year", "ja": "会計年度", "ex": "Our fiscal year ends in March.", "exJa": "当社の年度は3月末です", "cat": 3},
  {"n": 101, "en": "first half", "ja": "上期", "ex": "We met the first half target.", "exJa": "上期目標を達成しました", "cat": 3},
  {"n": 102, "en": "second half", "ja": "下期", "ex": "The launch is in the second half.", "exJa": "発売は下期です", "cat": 3},
  {"n": 103, "en": "year-end", "ja": "年度末", "ex": "Year-end is always busy.", "exJa": "年度末はいつも忙しいです", "cat": 3},
  {"n": 104, "en": "annual", "ja": "年次の", "ex": "We hold an annual review.", "exJa": "年次の見直しを行います", "cat": 3},
  {"n": 105, "en": "quarterly", "ja": "四半期ごとの", "ex": "We report quarterly.", "exJa": "四半期ごとに報告します", "cat": 3},
  {"n": 106, "en": "biweekly", "ja": "隔週の", "ex": "We have a biweekly call.", "exJa": "隔週で打ち合わせがあります", "cat": 3},
  {"n": 107, "en": "availability", "ja": "空き状況", "ex": "Please share your availability.", "exJa": "空き状況を教えてください", "cat": 3},
  {"n": 108, "en": "slot", "ja": "時間枠", "ex": "I have a slot at three.", "exJa": "3時なら空いています", "cat": 3},
  {"n": 109, "en": "in advance", "ja": "前もって", "ex": "Please let me know in advance.", "exJa": "事前にお知らせください", "cat": 3},
  {"n": 110, "en": "ahead of schedule", "ja": "前倒しで", "ex": "We finished ahead of schedule.", "exJa": "予定より早く終わりました", "cat": 3},
  {"n": 111, "en": "behind schedule", "ja": "予定より遅れて", "ex": "The project is behind schedule.", "exJa": "計画は遅れています", "cat": 3},
  {"n": 112, "en": "on track", "ja": "順調に進んで", "ex": "We are on track.", "exJa": "順調に進んでいます", "cat": 3},
  {"n": 113, "en": "delay", "ja": "遅延／遅らせる", "ex": "The delay cost us money.", "exJa": "遅れで損失が出ました", "cat": 3},
  {"n": 114, "en": "grace period", "ja": "猶予期間", "ex": "There is a 30-day grace period.", "exJa": "30日の猶予があります", "cat": 3},
  {"n": 115, "en": "extension", "ja": "延長", "ex": "We asked for an extension.", "exJa": "延長をお願いしました", "cat": 3},
  {"n": 116, "en": "expedite", "ja": "急いで進める", "ex": "Can you expedite the shipment?", "exJa": "出荷を早められますか", "cat": 3},
  {"n": 117, "en": "buffer", "ja": "余裕、予備", "ex": "Add two days as a buffer.", "exJa": "余裕を2日見てください", "cat": 3},
  {"n": 118, "en": "tentative", "ja": "仮の、暫定の", "ex": "This is a tentative plan.", "exJa": "これは仮の計画です", "cat": 3},
  {"n": 119, "en": "finalize", "ja": "確定させる", "ex": "Let's finalize the price.", "exJa": "価格を確定しましょう", "cat": 3},
  {"n": 120, "en": "commitment", "ja": "確約", "ex": "I need a firm commitment.", "exJa": "確約が必要です", "cat": 3},
  {"n": 121, "en": "priority", "ja": "優先度", "ex": "This has top priority.", "exJa": "これが最優先です", "cat": 3},
  {"n": 122, "en": "urgency", "ja": "緊急度", "ex": "I understand the urgency.", "exJa": "緊急度は理解しています", "cat": 3},
  {"n": 123, "en": "frequency", "ja": "頻度", "ex": "Increase the reporting frequency.", "exJa": "報告の頻度を上げてください", "cat": 3},
  {"n": 124, "en": "recurring", "ja": "繰り返し発生する", "ex": "This is a recurring problem.", "exJa": "これは繰り返し起きる問題です", "cat": 3},
  {"n": 125, "en": "overdue", "ja": "期限を過ぎた", "ex": "The payment is overdue.", "exJa": "支払いが期限を過ぎています", "cat": 3},
  {"n": 126, "en": "headquarters", "ja": "本社", "ex": "Our headquarters is in Yokohama.", "exJa": "本社は横浜です", "cat": 4},
  {"n": 127, "en": "subsidiary", "ja": "子会社", "ex": "They set up a subsidiary in Asia.", "exJa": "アジアに子会社を設立しました", "cat": 4},
  {"n": 128, "en": "affiliate", "ja": "関連会社", "ex": "He works at an affiliate.", "exJa": "彼は関連会社で働いています", "cat": 4},
  {"n": 129, "en": "division", "ja": "事業部", "ex": "I moved to the sales division.", "exJa": "営業事業部に移りました", "cat": 4},
  {"n": 130, "en": "department", "ja": "部署", "ex": "Which department are you in?", "exJa": "どの部署ですか", "cat": 4},
  {"n": 131, "en": "unit", "ja": "部門、単位", "ex": "Our unit has eight people.", "exJa": "この部門は8人です", "cat": 4},
  {"n": 132, "en": "hierarchy", "ja": "組織階層", "ex": "The hierarchy is very flat.", "exJa": "階層はとても浅いです", "cat": 4},
  {"n": 133, "en": "executive", "ja": "経営幹部", "ex": "The executives approved it.", "exJa": "幹部が承認しました", "cat": 4},
  {"n": 134, "en": "board", "ja": "取締役会", "ex": "The board meets in May.", "exJa": "取締役会は5月です", "cat": 4},
  {"n": 135, "en": "stakeholder", "ja": "利害関係者", "ex": "Let's list the stakeholders.", "exJa": "関係者を洗い出しましょう", "cat": 4},
  {"n": 136, "en": "supervisor", "ja": "監督する立場の人", "ex": "Ask your supervisor first.", "exJa": "まず上長に聞いてください", "cat": 4},
  {"n": 137, "en": "subordinate", "ja": "部下", "ex": "He has five subordinates.", "exJa": "部下が5人います", "cat": 4},
  {"n": 138, "en": "colleague", "ja": "同僚", "ex": "A colleague helped me.", "exJa": "同僚が助けてくれました", "cat": 4},
  {"n": 139, "en": "counterpart", "ja": "先方の同じ立場の人", "ex": "I met my counterpart in Taiwan.", "exJa": "台湾の担当者に会いました", "cat": 4},
  {"n": 140, "en": "successor", "ja": "後任", "ex": "We are looking for a successor.", "exJa": "後任を探しています", "cat": 4},
  {"n": 141, "en": "predecessor", "ja": "前任者", "ex": "My predecessor started this.", "exJa": "前任者が始めました", "cat": 4},
  {"n": 142, "en": "headcount", "ja": "人員数", "ex": "We need more headcount.", "exJa": "人員の増強が必要です", "cat": 4},
  {"n": 143, "en": "workforce", "ja": "従業員全体", "ex": "Half the workforce is remote.", "exJa": "従業員の半分は在宅です", "cat": 4},
  {"n": 144, "en": "recruitment", "ja": "採用活動", "ex": "Recruitment starts in April.", "exJa": "採用活動は4月からです", "cat": 4},
  {"n": 145, "en": "candidate", "ja": "候補者", "ex": "We have three candidates.", "exJa": "候補者は3名です", "cat": 4},
  {"n": 146, "en": "applicant", "ja": "応募者", "ex": "The applicant has good skills.", "exJa": "応募者は良い技能があります", "cat": 4},
  {"n": 147, "en": "resume", "ja": "履歴書", "ex": "Please send your resume.", "exJa": "履歴書を送ってください", "cat": 4},
  {"n": 148, "en": "onboarding", "ja": "受け入れと立ち上がり支援", "ex": "Onboarding takes two weeks.", "exJa": "受け入れ研修は2週間です", "cat": 4},
  {"n": 149, "en": "orientation", "ja": "導入研修", "ex": "Orientation is on Monday.", "exJa": "導入研修は月曜です", "cat": 4},
  {"n": 150, "en": "mentor", "ja": "指導役", "ex": "She is my mentor.", "exJa": "彼女は私の指導役です", "cat": 4},
  {"n": 151, "en": "appraisal", "ja": "人事評価", "ex": "The appraisal is once a year.", "exJa": "評価は年に一度です", "cat": 4},
  {"n": 152, "en": "feedback", "ja": "評価や意見を返すこと", "ex": "Thank you for the feedback.", "exJa": "ご意見ありがとうございます", "cat": 4},
  {"n": 153, "en": "performance review", "ja": "業績評価面談", "ex": "My performance review is tomorrow.", "exJa": "評価面談は明日です", "cat": 4},
  {"n": 154, "en": "promotion", "ja": "昇進", "ex": "He got a promotion.", "exJa": "彼は昇進しました", "cat": 4},
  {"n": 155, "en": "assignment", "ja": "任命、担当業務", "ex": "This is a new assignment.", "exJa": "これは新しい担当業務です", "cat": 4},
  {"n": 156, "en": "transfer", "ja": "異動", "ex": "I got a transfer to Tokyo.", "exJa": "東京に異動になりました", "cat": 4},
  {"n": 157, "en": "resignation", "ja": "辞職", "ex": "She handed in her resignation.", "exJa": "彼女は辞表を出しました", "cat": 4},
  {"n": 158, "en": "retirement", "ja": "定年退職", "ex": "His retirement is next year.", "exJa": "彼の定年は来年です", "cat": 4},
  {"n": 159, "en": "turnover", "ja": "離職率、回転", "ex": "Turnover is high in sales.", "exJa": "営業は離職率が高いです", "cat": 4},
  {"n": 160, "en": "payroll", "ja": "給与支払い業務", "ex": "Payroll is handled by HR.", "exJa": "給与業務は人事が担当します", "cat": 4},
  {"n": 161, "en": "salary", "ja": "給与", "ex": "The salary is negotiable.", "exJa": "給与は相談可能です", "cat": 4},
  {"n": 162, "en": "compensation", "ja": "報酬全体", "ex": "The compensation includes a bonus.", "exJa": "報酬には賞与が含まれます", "cat": 4},
  {"n": 163, "en": "benefits", "ja": "福利厚生", "ex": "The benefits are good here.", "exJa": "ここは福利厚生が良いです", "cat": 4},
  {"n": 164, "en": "allowance", "ja": "手当", "ex": "I get a travel allowance.", "exJa": "交通手当が出ます", "cat": 4},
  {"n": 165, "en": "overtime", "ja": "残業", "ex": "I did overtime last night.", "exJa": "昨夜は残業しました", "cat": 4},
  {"n": 166, "en": "leave", "ja": "休暇", "ex": "He is on leave this week.", "exJa": "彼は今週休暇です", "cat": 4},
  {"n": 167, "en": "shift", "ja": "勤務時間帯", "ex": "My shift starts at eight.", "exJa": "勤務は8時からです", "cat": 4},
  {"n": 168, "en": "remote work", "ja": "在宅・遠隔勤務", "ex": "Remote work is allowed.", "exJa": "在宅勤務が認められています", "cat": 4},
  {"n": 169, "en": "job description", "ja": "職務内容の定義", "ex": "Check the job description.", "exJa": "職務内容を確認してください", "cat": 4},
  {"n": 170, "en": "responsibility", "ja": "職責", "ex": "That is my responsibility.", "exJa": "それは私の職責です", "cat": 4},
  {"n": 171, "en": "prospect", "ja": "見込み客", "ex": "We have ten new prospects.", "exJa": "新規の見込み客が10社あります", "cat": 5},
  {"n": 172, "en": "lead", "ja": "見込み案件", "ex": "This lead looks promising.", "exJa": "この案件は有望です", "cat": 5},
  {"n": 173, "en": "pipeline", "ja": "案件の積み上がり", "ex": "My pipeline is thin.", "exJa": "案件の積み上がりが薄いです", "cat": 5},
  {"n": 174, "en": "opportunity", "ja": "商談", "ex": "A big opportunity came up.", "exJa": "大型商談が出てきました", "cat": 5},
  {"n": 175, "en": "account", "ja": "担当顧客", "ex": "I manage twenty accounts.", "exJa": "20社を担当しています", "cat": 5},
  {"n": 176, "en": "end user", "ja": "最終利用者", "ex": "The end user is a factory.", "exJa": "最終利用者は工場です", "cat": 5},
  {"n": 177, "en": "decision maker", "ja": "決裁者", "ex": "Who is the decision maker?", "exJa": "決裁者は誰ですか", "cat": 5},
  {"n": 178, "en": "referral", "ja": "紹介", "ex": "We got a referral from a partner.", "exJa": "パートナーから紹介を受けました", "cat": 5},
  {"n": 179, "en": "forecast", "ja": "見込み予測", "ex": "Update your forecast weekly.", "exJa": "見込みを毎週更新してください", "cat": 5},
  {"n": 180, "en": "quota", "ja": "課された販売目標", "ex": "He hit his quota.", "exJa": "彼は目標を達成しました", "cat": 5},
  {"n": 181, "en": "target", "ja": "目標値", "ex": "The target is too high.", "exJa": "目標が高すぎます", "cat": 5},
  {"n": 182, "en": "achievement", "ja": "達成", "ex": "That is a great achievement.", "exJa": "見事な達成です", "cat": 5},
  {"n": 183, "en": "proposal", "ja": "提案書", "ex": "I'll send the proposal today.", "exJa": "本日提案書を送ります", "cat": 5},
  {"n": 184, "en": "quotation", "ja": "見積書", "ex": "The quotation is ready.", "exJa": "見積書ができています", "cat": 5},
  {"n": 185, "en": "estimate", "ja": "概算", "ex": "This is a rough estimate.", "exJa": "これは概算です", "cat": 5},
  {"n": 186, "en": "discount", "ja": "値引き", "ex": "Can you give a discount?", "exJa": "値引きは可能ですか", "cat": 5},
  {"n": 187, "en": "margin", "ja": "利幅", "ex": "The margin is very thin.", "exJa": "利幅がとても薄いです", "cat": 5},
  {"n": 188, "en": "negotiation", "ja": "交渉", "ex": "The negotiation took a month.", "exJa": "交渉は1か月かかりました", "cat": 5},
  {"n": 189, "en": "negotiate", "ja": "交渉する", "ex": "We negotiated the price.", "exJa": "価格を交渉しました", "cat": 5},
  {"n": 190, "en": "concession", "ja": "譲歩", "ex": "We made a small concession.", "exJa": "少し譲歩しました", "cat": 5},
  {"n": 191, "en": "pushback", "ja": "難色、反発", "ex": "We got pushback on the price.", "exJa": "価格で難色を示されました", "cat": 5},
  {"n": 192, "en": "close", "ja": "契約をまとめる", "ex": "I want to close this month.", "exJa": "今月中に決めたいです", "cat": 5},
  {"n": 193, "en": "closing", "ja": "契約成立", "ex": "The closing is delayed.", "exJa": "契約成立が遅れています", "cat": 5},
  {"n": 194, "en": "win rate", "ja": "受注率", "ex": "Our win rate improved.", "exJa": "受注率が上がりました", "cat": 5},
  {"n": 195, "en": "churn", "ja": "解約、離反", "ex": "Churn increased last year.", "exJa": "昨年は解約が増えました", "cat": 5},
  {"n": 196, "en": "retention", "ja": "継続してもらうこと", "ex": "Retention is our priority.", "exJa": "継続利用が最優先です", "cat": 5},
  {"n": 197, "en": "renewal", "ja": "契約更新", "ex": "The renewal is in June.", "exJa": "更新は6月です", "cat": 5},
  {"n": 198, "en": "upsell", "ja": "上位品を提案する", "ex": "We tried to upsell the model.", "exJa": "上位機種を提案しました", "cat": 5},
  {"n": 199, "en": "cross-sell", "ja": "別商材を併せて提案する", "ex": "Let's cross-sell the software.", "exJa": "ソフトも併せて提案しましょう", "cat": 5},
  {"n": 200, "en": "segment", "ja": "顧客層、区分", "ex": "This segment is growing.", "exJa": "この層は伸びています", "cat": 5},
  {"n": 201, "en": "market share", "ja": "市場シェア", "ex": "We gained market share.", "exJa": "シェアを伸ばしました", "cat": 5},
  {"n": 202, "en": "competitor", "ja": "競合他社", "ex": "Our competitor is cheaper.", "exJa": "競合の方が安いです", "cat": 5},
  {"n": 203, "en": "competitive", "ja": "競争力のある", "ex": "The price is competitive.", "exJa": "価格は競争力があります", "cat": 5},
  {"n": 204, "en": "differentiation", "ja": "差別化", "ex": "We need clear differentiation.", "exJa": "明確な差別化が必要です", "cat": 5},
  {"n": 205, "en": "positioning", "ja": "位置づけ", "ex": "Our positioning is premium.", "exJa": "当社は高価格帯の位置づけです", "cat": 5},
  {"n": 206, "en": "value proposition", "ja": "提供価値", "ex": "Explain your value proposition.", "exJa": "提供価値を説明してください", "cat": 5},
  {"n": 207, "en": "use case", "ja": "活用場面", "ex": "Show a real use case.", "exJa": "実際の活用例を示してください", "cat": 5},
  {"n": 208, "en": "case study", "ja": "導入事例", "ex": "I'll share a case study.", "exJa": "導入事例を共有します", "cat": 5},
  {"n": 209, "en": "testimonial", "ja": "顧客の推薦の声", "ex": "The testimonial helped a lot.", "exJa": "顧客の声が効きました", "cat": 5},
  {"n": 210, "en": "demand", "ja": "需要", "ex": "Demand is growing fast.", "exJa": "需要が急拡大しています", "cat": 5},
  {"n": 211, "en": "supply", "ja": "供給", "ex": "Supply is still tight.", "exJa": "供給は依然逼迫しています", "cat": 5},
  {"n": 212, "en": "campaign", "ja": "販促の取り組み", "ex": "The campaign ends in May.", "exJa": "キャンペーンは5月までです", "cat": 5},
  {"n": 213, "en": "lead generation", "ja": "見込み客の獲得", "ex": "The event is for lead generation.", "exJa": "この催しは見込み客獲得が目的です", "cat": 5},
  {"n": 214, "en": "engagement", "ja": "関与、接点づくり", "ex": "Customer engagement is low.", "exJa": "顧客の関与が低いです", "cat": 5},
  {"n": 215, "en": "satisfaction", "ja": "満足度", "ex": "Satisfaction scores improved.", "exJa": "満足度が上がりました", "cat": 5},
  {"n": 216, "en": "complaint", "ja": "苦情", "ex": "We received a complaint.", "exJa": "苦情を受けました", "cat": 5},
  {"n": 217, "en": "escalation", "ja": "上位者への引き上げ", "ex": "This needs escalation.", "exJa": "これは上位対応が必要です", "cat": 5},
  {"n": 218, "en": "loyalty", "ja": "継続的な支持", "ex": "Brand loyalty is strong.", "exJa": "ブランドへの支持が強いです", "cat": 5},
  {"n": 219, "en": "territory", "ja": "担当領域・地域", "ex": "My territory is western Japan.", "exJa": "担当は西日本です", "cat": 5},
  {"n": 220, "en": "channel", "ja": "販売経路", "ex": "We sell through two channels.", "exJa": "2つの経路で販売しています", "cat": 5},
  {"n": 221, "en": "revenue", "ja": "売上高", "ex": "Revenue rose ten percent.", "exJa": "売上高が10%伸びました", "cat": 6},
  {"n": 222, "en": "figure", "ja": "数値", "ex": "Check the latest figures.", "exJa": "最新の数値を確認してください", "cat": 6},
  {"n": 223, "en": "profit", "ja": "利益", "ex": "Profit fell this year.", "exJa": "今年は利益が落ちました", "cat": 6},
  {"n": 224, "en": "gross profit", "ja": "粗利", "ex": "Gross profit is improving.", "exJa": "粗利が改善しています", "cat": 6},
  {"n": 225, "en": "net", "ja": "正味の、差引後の", "ex": "Net sales were strong.", "exJa": "純売上は好調でした", "cat": 6},
  {"n": 226, "en": "loss", "ja": "損失", "ex": "We had a small loss.", "exJa": "少額の損失が出ました", "cat": 6},
  {"n": 227, "en": "breakeven", "ja": "損益がとんとんになる点", "ex": "We reached breakeven.", "exJa": "損益分岐点に達しました", "cat": 6},
  {"n": 228, "en": "cost", "ja": "原価、費用", "ex": "The cost is too high.", "exJa": "原価が高すぎます", "cat": 6},
  {"n": 229, "en": "expense", "ja": "経費", "ex": "Please submit your expenses.", "exJa": "経費を提出してください", "cat": 6},
  {"n": 230, "en": "expenditure", "ja": "支出", "ex": "Cut unnecessary expenditure.", "exJa": "不要な支出を削ってください", "cat": 6},
  {"n": 231, "en": "budget", "ja": "予算", "ex": "The budget is fixed.", "exJa": "予算は決まっています", "cat": 6},
  {"n": 232, "en": "allocate", "ja": "配分する", "ex": "We allocated more budget.", "exJa": "予算を追加配分しました", "cat": 6},
  {"n": 233, "en": "allocation", "ja": "配分", "ex": "The allocation is unfair.", "exJa": "配分が不公平です", "cat": 6},
  {"n": 234, "en": "variance", "ja": "差異", "ex": "Explain the variance.", "exJa": "差異を説明してください", "cat": 6},
  {"n": 235, "en": "actual", "ja": "実績値", "ex": "Actuals beat the plan.", "exJa": "実績が計画を上回りました", "cat": 6},
  {"n": 236, "en": "projection", "ja": "将来の見通し", "ex": "The projection looks optimistic.", "exJa": "見通しは楽観的です", "cat": 6},
  {"n": 237, "en": "invoice", "ja": "請求書", "ex": "The invoice was sent.", "exJa": "請求書を送りました", "cat": 6},
  {"n": 238, "en": "billing", "ja": "請求業務", "ex": "Billing is done monthly.", "exJa": "請求は毎月です", "cat": 6},
  {"n": 239, "en": "payment terms", "ja": "支払い条件", "ex": "What are your payment terms?", "exJa": "支払い条件を教えてください", "cat": 6},
  {"n": 240, "en": "prepayment", "ja": "前払い", "ex": "They asked for prepayment.", "exJa": "前払いを求められました", "cat": 6},
  {"n": 241, "en": "outstanding", "ja": "未払いの、未解決の", "ex": "The balance is still outstanding.", "exJa": "残高が未払いです", "cat": 6},
  {"n": 242, "en": "settlement", "ja": "決済、精算", "ex": "Settlement takes three days.", "exJa": "決済に3日かかります", "cat": 6},
  {"n": 243, "en": "reimbursement", "ja": "立替分の払い戻し", "ex": "I applied for reimbursement.", "exJa": "精算を申請しました", "cat": 6},
  {"n": 244, "en": "deposit", "ja": "手付金、入金", "ex": "We paid a deposit.", "exJa": "手付金を支払いました", "cat": 6},
  {"n": 245, "en": "installment", "ja": "分割払い", "ex": "Pay in three installments.", "exJa": "3回の分割で支払ってください", "cat": 6},
  {"n": 246, "en": "subscription", "ja": "定額契約", "ex": "The subscription renews yearly.", "exJa": "定額契約は毎年更新です", "cat": 6},
  {"n": 247, "en": "price list", "ja": "価格表", "ex": "Send me the latest price list.", "exJa": "最新の価格表を送ってください", "cat": 6},
  {"n": 248, "en": "cash flow", "ja": "資金の流れ", "ex": "Cash flow is tight.", "exJa": "資金繰りが厳しいです", "cat": 6},
  {"n": 249, "en": "asset", "ja": "資産", "ex": "The factory is a key asset.", "exJa": "工場は主要な資産です", "cat": 6},
  {"n": 250, "en": "liability", "ja": "負債", "ex": "They reduced their liabilities.", "exJa": "負債を減らしました", "cat": 6},
  {"n": 251, "en": "equity", "ja": "自己資本", "ex": "Equity increased this year.", "exJa": "自己資本が増えました", "cat": 6},
  {"n": 252, "en": "capital", "ja": "資本", "ex": "We need more capital.", "exJa": "資本が必要です", "cat": 6},
  {"n": 253, "en": "investment", "ja": "投資", "ex": "This is a long-term investment.", "exJa": "これは長期投資です", "cat": 6},
  {"n": 254, "en": "ROI", "ja": "投資対効果", "ex": "What is the expected ROI?", "exJa": "想定の投資対効果は何ですか", "cat": 6},
  {"n": 255, "en": "depreciation", "ja": "減価償却", "ex": "Depreciation lowers the profit.", "exJa": "減価償却で利益が下がります", "cat": 6},
  {"n": 256, "en": "tax", "ja": "税", "ex": "The price includes tax.", "exJa": "価格は税込みです", "cat": 6},
  {"n": 257, "en": "VAT", "ja": "付加価値税", "ex": "VAT is twenty percent there.", "exJa": "現地の付加価値税は20%です", "cat": 6},
  {"n": 258, "en": "currency", "ja": "通貨", "ex": "We quote in local currency.", "exJa": "現地通貨で見積もります", "cat": 6},
  {"n": 259, "en": "exchange rate", "ja": "為替レート", "ex": "The exchange rate changed.", "exJa": "為替レートが変わりました", "cat": 6},
  {"n": 260, "en": "inflation", "ja": "物価上昇", "ex": "Inflation raised our costs.", "exJa": "物価上昇で原価が上がりました", "cat": 6},
  {"n": 261, "en": "audit", "ja": "監査", "ex": "The audit starts next week.", "exJa": "監査は来週からです", "cat": 6},
  {"n": 262, "en": "accounting", "ja": "経理", "ex": "Ask the accounting team.", "exJa": "経理に聞いてください", "cat": 6},
  {"n": 263, "en": "statement", "ja": "計算書、明細", "ex": "Check the bank statement.", "exJa": "取引明細を確認してください", "cat": 6},
  {"n": 264, "en": "balance", "ja": "残高", "ex": "The balance is zero.", "exJa": "残高はゼロです", "cat": 6},
  {"n": 265, "en": "subtotal", "ja": "小計", "ex": "The subtotal excludes tax.", "exJa": "小計は税抜きです", "cat": 6},
  {"n": 266, "en": "breakdown", "ja": "内訳", "ex": "Send me a cost breakdown.", "exJa": "原価の内訳を送ってください", "cat": 6},
  {"n": 267, "en": "percentage", "ja": "割合", "ex": "What percentage is that?", "exJa": "それは何%ですか", "cat": 6},
  {"n": 268, "en": "growth rate", "ja": "成長率", "ex": "The growth rate slowed.", "exJa": "成長率が鈍りました", "cat": 6},
  {"n": 269, "en": "average", "ja": "平均", "ex": "The average is above target.", "exJa": "平均は目標を上回っています", "cat": 6},
  {"n": 270, "en": "benchmark", "ja": "比較の基準", "ex": "Use last year as a benchmark.", "exJa": "昨年を基準にしてください", "cat": 6},
  {"n": 271, "en": "scope", "ja": "業務範囲", "ex": "That is out of scope.", "exJa": "それは範囲外です", "cat": 7},
  {"n": 272, "en": "deliverable", "ja": "成果物", "ex": "List the deliverables.", "exJa": "成果物を列挙してください", "cat": 7},
  {"n": 273, "en": "objective", "ja": "達成すべき目的", "ex": "Our objective is simple.", "exJa": "目的は単純です", "cat": 7},
  {"n": 274, "en": "requirement", "ja": "要件", "ex": "The requirements changed.", "exJa": "要件が変わりました", "cat": 7},
  {"n": 275, "en": "specification", "ja": "仕様", "ex": "Send the detailed specification.", "exJa": "詳細仕様を送ってください", "cat": 7},
  {"n": 276, "en": "assumption", "ja": "前提", "ex": "That assumption may be wrong.", "exJa": "その前提は誤りかもしれません", "cat": 7},
  {"n": 277, "en": "constraint", "ja": "制約", "ex": "Time is our main constraint.", "exJa": "時間が主な制約です", "cat": 7},
  {"n": 278, "en": "dependency", "ja": "依存関係", "ex": "There is a dependency on IT.", "exJa": "IT部門への依存があります", "cat": 7},
  {"n": 279, "en": "prerequisite", "ja": "前提条件", "ex": "Training is a prerequisite.", "exJa": "研修が前提条件です", "cat": 7},
  {"n": 280, "en": "phase", "ja": "段階", "ex": "We are in phase two.", "exJa": "第2段階です", "cat": 7},
  {"n": 281, "en": "progress", "ja": "進捗", "ex": "Report the progress weekly.", "exJa": "進捗を毎週報告してください", "cat": 7},
  {"n": 282, "en": "status update", "ja": "状況報告", "ex": "I need a status update.", "exJa": "状況報告をください", "cat": 7},
  {"n": 283, "en": "blocker", "ja": "進行を止めている要因", "ex": "What is the current blocker?", "exJa": "今の障害は何ですか", "cat": 7},
  {"n": 284, "en": "bottleneck", "ja": "詰まっている箇所", "ex": "Testing is the bottleneck.", "exJa": "試験が詰まりの原因です", "cat": 7},
  {"n": 285, "en": "issue", "ja": "課題", "ex": "We found a serious issue.", "exJa": "重大な課題が見つかりました", "cat": 7},
  {"n": 286, "en": "risk", "ja": "リスク", "ex": "The risk is acceptable.", "exJa": "許容できるリスクです", "cat": 7},
  {"n": 287, "en": "mitigate", "ja": "影響を和らげる", "ex": "How can we mitigate this?", "exJa": "どう軽減できますか", "cat": 7},
  {"n": 288, "en": "contingency", "ja": "不測の事態への備え", "ex": "We need a contingency plan.", "exJa": "代替の備えが必要です", "cat": 7},
  {"n": 289, "en": "workaround", "ja": "暫定の回避策", "ex": "We found a workaround.", "exJa": "回避策が見つかりました", "cat": 7},
  {"n": 290, "en": "root cause", "ja": "根本原因", "ex": "Find the root cause first.", "exJa": "まず根本原因を突き止めてください", "cat": 7},
  {"n": 291, "en": "resolution", "ja": "解決、決着", "ex": "The resolution took two days.", "exJa": "解決に2日かかりました", "cat": 7},
  {"n": 292, "en": "escalate", "ja": "上位に判断を仰ぐ", "ex": "I had to escalate the issue.", "exJa": "課題を上位に上げました", "cat": 7},
  {"n": 293, "en": "approval", "ja": "承認", "ex": "We are waiting for approval.", "exJa": "承認待ちです", "cat": 7},
  {"n": 294, "en": "sign-off", "ja": "最終承認", "ex": "I need your sign-off.", "exJa": "最終承認をお願いします", "cat": 7},
  {"n": 295, "en": "governance", "ja": "統制・運営の仕組み", "ex": "The governance is unclear.", "exJa": "運営の仕組みが不明確です", "cat": 7},
  {"n": 296, "en": "ownership", "ja": "自分ごととしての責任", "ex": "Take ownership of this task.", "exJa": "この仕事を自分ごととして進めてください", "cat": 7},
  {"n": 297, "en": "accountability", "ja": "説明責任", "ex": "Accountability sits with me.", "exJa": "説明責任は私にあります", "cat": 7},
  {"n": 298, "en": "delegate", "ja": "権限を委ねる", "ex": "Delegate this to your team.", "exJa": "これはチームに任せてください", "cat": 7},
  {"n": 299, "en": "coordinate", "ja": "段取りを調整する", "ex": "I'll coordinate with the factory.", "exJa": "工場と調整します", "cat": 7},
  {"n": 300, "en": "collaborate", "ja": "協働する", "ex": "We collaborate with a partner.", "exJa": "パートナーと協働しています", "cat": 7},
  {"n": 301, "en": "streamline", "ja": "無駄をなくして効率化する", "ex": "We streamlined the process.", "exJa": "工程を効率化しました", "cat": 7},
  {"n": 302, "en": "optimize", "ja": "最適化する", "ex": "Optimize the layout first.", "exJa": "まず配置を最適化してください", "cat": 7},
  {"n": 303, "en": "standardize", "ja": "標準化する", "ex": "Let's standardize the format.", "exJa": "書式を標準化しましょう", "cat": 7},
  {"n": 304, "en": "implement", "ja": "実行に移す、導入する", "ex": "We implemented the new rule.", "exJa": "新ルールを導入しました", "cat": 7},
  {"n": 305, "en": "implementation", "ja": "導入、実施", "ex": "Implementation starts in June.", "exJa": "導入は6月開始です", "cat": 7},
  {"n": 306, "en": "execution", "ja": "実行", "ex": "The plan is good, but execution is hard.", "exJa": "計画は良いが実行が難しいです", "cat": 7},
  {"n": 307, "en": "rollout", "ja": "段階的な展開", "ex": "The rollout covers ten sites.", "exJa": "展開は10拠点です", "cat": 7},
  {"n": 308, "en": "pilot", "ja": "試験的導入", "ex": "We ran a pilot last month.", "exJa": "先月、試験導入をしました", "cat": 7},
  {"n": 309, "en": "scalability", "ja": "拡張のしやすさ", "ex": "Scalability is a concern.", "exJa": "拡張性が懸念です", "cat": 7},
  {"n": 310, "en": "capacity", "ja": "対応できる量", "ex": "We have no capacity now.", "exJa": "今は対応する余力がありません", "cat": 7},
  {"n": 311, "en": "bandwidth", "ja": "対応できる余力", "ex": "I don't have the bandwidth.", "exJa": "手が回りません", "cat": 7},
  {"n": 312, "en": "workload", "ja": "業務負荷", "ex": "His workload is too heavy.", "exJa": "彼の業務負荷が重すぎます", "cat": 7},
  {"n": 313, "en": "checkpoint", "ja": "確認の節目", "ex": "Set a checkpoint in March.", "exJa": "3月に確認の節目を置きましょう", "cat": 7},
  {"n": 314, "en": "documentation", "ja": "文書化された資料", "ex": "The documentation is missing.", "exJa": "資料が足りません", "cat": 7},
  {"n": 315, "en": "template", "ja": "ひな形", "ex": "Use the standard template.", "exJa": "標準のひな形を使ってください", "cat": 7},
  {"n": 316, "en": "checklist", "ja": "確認一覧", "ex": "Follow the checklist.", "exJa": "確認表に沿って進めてください", "cat": 7},
  {"n": 317, "en": "KPI", "ja": "重要業績指標", "ex": "What are the KPIs?", "exJa": "重要指標は何ですか", "cat": 7},
  {"n": 318, "en": "metrics", "ja": "測る指標", "ex": "We track three metrics.", "exJa": "3つの指標を追っています", "cat": 7},
  {"n": 319, "en": "outcome", "ja": "得られた成果", "ex": "The outcome was positive.", "exJa": "成果は良好でした", "cat": 7},
  {"n": 320, "en": "lessons learned", "ja": "得られた教訓", "ex": "Let's record the lessons learned.", "exJa": "得た教訓を記録しましょう", "cat": 7},
  {"n": 321, "en": "feature", "ja": "特長となる機能", "ex": "This feature is new.", "exJa": "この機能は新しいです", "cat": 8},
  {"n": 322, "en": "functionality", "ja": "機能面、機能性", "ex": "The functionality is limited.", "exJa": "機能が限られています", "cat": 8},
  {"n": 323, "en": "performance", "ja": "性能", "ex": "Performance improved by thirty percent.", "exJa": "性能が30%向上しました", "cat": 8},
  {"n": 324, "en": "reliability", "ja": "信頼性", "ex": "Reliability matters most.", "exJa": "信頼性が最も重要です", "cat": 8},
  {"n": 325, "en": "durability", "ja": "耐久性", "ex": "Durability was tested.", "exJa": "耐久性を試験しました", "cat": 8},
  {"n": 326, "en": "compatibility", "ja": "互換性", "ex": "Check the compatibility first.", "exJa": "先に互換性を確認してください", "cat": 8},
  {"n": 327, "en": "interface", "ja": "接続部分、操作面", "ex": "The interface is simple.", "exJa": "操作画面は単純です", "cat": 8},
  {"n": 328, "en": "architecture", "ja": "全体構成", "ex": "Explain the system architecture.", "exJa": "システム構成を説明してください", "cat": 8},
  {"n": 329, "en": "infrastructure", "ja": "基盤設備", "ex": "The infrastructure is old.", "exJa": "基盤設備が古いです", "cat": 8},
  {"n": 330, "en": "platform", "ja": "土台となる基盤", "ex": "We built it on their platform.", "exJa": "彼らの基盤上に構築しました", "cat": 8},
  {"n": 331, "en": "component", "ja": "構成部品", "ex": "One component is missing.", "exJa": "部品が一つ足りません", "cat": 8},
  {"n": 332, "en": "module", "ja": "構成単位", "ex": "Add a second module.", "exJa": "2つ目のモジュールを追加してください", "cat": 8},
  {"n": 333, "en": "prototype", "ja": "試作品", "ex": "The prototype works well.", "exJa": "試作品はうまく動いています", "cat": 8},
  {"n": 334, "en": "PoC", "ja": "概念実証", "ex": "The PoC lasts three months.", "exJa": "実証は3か月です", "cat": 8},
  {"n": 335, "en": "demonstration", "ja": "実演", "ex": "We gave a demonstration.", "exJa": "実演を行いました", "cat": 8},
  {"n": 336, "en": "trial", "ja": "試用", "ex": "Start with a free trial.", "exJa": "無料試用から始めてください", "cat": 8},
  {"n": 337, "en": "deployment", "ja": "導入・展開", "ex": "Deployment finished last week.", "exJa": "導入は先週完了しました", "cat": 8},
  {"n": 338, "en": "integration", "ja": "統合", "ex": "The integration failed once.", "exJa": "統合が一度失敗しました", "cat": 8},
  {"n": 339, "en": "configuration", "ja": "設定内容", "ex": "Save the configuration.", "exJa": "設定を保存してください", "cat": 8},
  {"n": 340, "en": "customization", "ja": "個別仕様への作り込み", "ex": "Customization costs extra.", "exJa": "個別対応は別料金です", "cat": 8},
  {"n": 341, "en": "migration", "ja": "移行", "ex": "Data migration takes time.", "exJa": "データ移行は時間がかかります", "cat": 8},
  {"n": 342, "en": "upgrade", "ja": "上位版への更新", "ex": "The upgrade is free.", "exJa": "更新は無料です", "cat": 8},
  {"n": 343, "en": "patch", "ja": "修正プログラム", "ex": "Apply the latest patch.", "exJa": "最新の修正を適用してください", "cat": 8},
  {"n": 344, "en": "maintenance", "ja": "保守", "ex": "Maintenance is on Sunday.", "exJa": "保守は日曜です", "cat": 8},
  {"n": 345, "en": "downtime", "ja": "停止している時間", "ex": "Downtime must be short.", "exJa": "停止時間は短くすべきです", "cat": 8},
  {"n": 346, "en": "outage", "ja": "障害による停止", "ex": "There was a two-hour outage.", "exJa": "2時間の障害停止がありました", "cat": 8},
  {"n": 347, "en": "troubleshooting", "ja": "原因究明と対処", "ex": "Troubleshooting took all day.", "exJa": "原因対応に丸一日かかりました", "cat": 8},
  {"n": 348, "en": "defect", "ja": "欠陥", "ex": "We found a defect.", "exJa": "欠陥が見つかりました", "cat": 8},
  {"n": 349, "en": "malfunction", "ja": "誤作動", "ex": "The sensor had a malfunction.", "exJa": "センサーが誤作動しました", "cat": 8},
  {"n": 350, "en": "latency", "ja": "応答の遅れ", "ex": "Latency is too high.", "exJa": "応答の遅れが大きすぎます", "cat": 8},
  {"n": 351, "en": "throughput", "ja": "処理量", "ex": "Throughput doubled.", "exJa": "処理量が倍になりました", "cat": 8},
  {"n": 352, "en": "redundancy", "ja": "冗長構成", "ex": "We added redundancy.", "exJa": "冗長構成を加えました", "cat": 8},
  {"n": 353, "en": "backup", "ja": "予備、控え", "ex": "Keep a backup copy.", "exJa": "予備を残してください", "cat": 8},
  {"n": 354, "en": "recovery", "ja": "復旧", "ex": "Recovery took one hour.", "exJa": "復旧に1時間かかりました", "cat": 8},
  {"n": 355, "en": "security", "ja": "安全性の確保", "ex": "Security is the top concern.", "exJa": "安全性が最大の懸念です", "cat": 8},
  {"n": 356, "en": "vulnerability", "ja": "脆弱性", "ex": "They fixed the vulnerability.", "exJa": "脆弱性を修正しました", "cat": 8},
  {"n": 357, "en": "authentication", "ja": "本人確認", "ex": "Authentication failed twice.", "exJa": "認証が2回失敗しました", "cat": 8},
  {"n": 358, "en": "encryption", "ja": "暗号化", "ex": "All data uses encryption.", "exJa": "全データを暗号化しています", "cat": 8},
  {"n": 359, "en": "firewall", "ja": "防御の仕組み", "ex": "The firewall blocked it.", "exJa": "ファイアウォールが遮断しました", "cat": 8},
  {"n": 360, "en": "protocol", "ja": "通信規約、手順", "ex": "Which protocol do you use?", "exJa": "どの通信規約ですか", "cat": 8},
  {"n": 361, "en": "server", "ja": "サーバー", "ex": "The server is down.", "exJa": "サーバーが停止しています", "cat": 8},
  {"n": 362, "en": "cloud", "ja": "クラウド", "ex": "We moved to the cloud.", "exJa": "クラウドに移行しました", "cat": 8},
  {"n": 363, "en": "on-premise", "ja": "自社設置型", "ex": "They prefer on-premise.", "exJa": "先方は自社設置型を好みます", "cat": 8},
  {"n": 364, "en": "data center", "ja": "データセンター", "ex": "The data center is in Osaka.", "exJa": "データセンターは大阪です", "cat": 8},
  {"n": 365, "en": "algorithm", "ja": "計算手順", "ex": "The algorithm is efficient.", "exJa": "この計算手順は効率的です", "cat": 8},
  {"n": 366, "en": "model", "ja": "機種、学習モデル", "ex": "We trained a new model.", "exJa": "新しいモデルを学習させました", "cat": 8},
  {"n": 367, "en": "inference", "ja": "推論", "ex": "Inference runs on the device.", "exJa": "推論は機器側で動きます", "cat": 8},
  {"n": 368, "en": "training", "ja": "学習させること", "ex": "Training takes two days.", "exJa": "学習に2日かかります", "cat": 8},
  {"n": 369, "en": "automation", "ja": "自動化", "ex": "Automation reduced errors.", "exJa": "自動化で誤りが減りました", "cat": 8},
  {"n": 370, "en": "productivity", "ja": "生産性", "ex": "Productivity went up.", "exJa": "生産性が上がりました", "cat": 8},
  {"n": 371, "en": "distributor", "ja": "販売代理店", "ex": "We are their distributor in Japan.", "exJa": "当社は日本の代理店です", "cat": 9},
  {"n": 372, "en": "reseller", "ja": "再販業者", "ex": "The reseller handles support.", "exJa": "再販業者が支援を担当します", "cat": 9},
  {"n": 373, "en": "vendor", "ja": "仕入先、提供元", "ex": "Ask the vendor directly.", "exJa": "仕入先に直接聞いてください", "cat": 9},
  {"n": 374, "en": "supplier", "ja": "供給元", "ex": "We changed suppliers.", "exJa": "供給元を変えました", "cat": 9},
  {"n": 375, "en": "subcontractor", "ja": "下請け業者", "ex": "A subcontractor did the work.", "exJa": "下請けが作業しました", "cat": 9},
  {"n": 376, "en": "intermediary", "ja": "仲介者", "ex": "We act as an intermediary.", "exJa": "当社は仲介役です", "cat": 9},
  {"n": 377, "en": "agreement", "ja": "合意、契約書", "ex": "We signed the agreement.", "exJa": "契約書を締結しました", "cat": 9},
  {"n": 378, "en": "contract", "ja": "契約", "ex": "The contract expires in March.", "exJa": "契約は3月に終了します", "cat": 9},
  {"n": 379, "en": "clause", "ja": "条項", "ex": "Check clause five.", "exJa": "第5条を確認してください", "cat": 9},
  {"n": 380, "en": "terms and conditions", "ja": "契約条件", "ex": "Read the terms and conditions.", "exJa": "契約条件を読んでください", "cat": 9},
  {"n": 381, "en": "amendment", "ja": "変更契約", "ex": "We need an amendment.", "exJa": "変更契約が必要です", "cat": 9},
  {"n": 382, "en": "NDA", "ja": "秘密保持契約", "ex": "Let's conclude an NDA first.", "exJa": "先に秘密保持契約を結びましょう", "cat": 9},
  {"n": 383, "en": "obligation", "ja": "義務", "ex": "We have no obligation to pay.", "exJa": "支払う義務はありません", "cat": 9},
  {"n": 384, "en": "compliance", "ja": "法令遵守", "ex": "Compliance training is required.", "exJa": "法令遵守研修は必須です", "cat": 9},
  {"n": 385, "en": "regulation", "ja": "規制", "ex": "New regulations start in July.", "exJa": "新しい規制が7月に始まります", "cat": 9},
  {"n": 386, "en": "certification", "ja": "認証、認定", "ex": "The product has safety certification.", "exJa": "製品は安全認証を取得しています", "cat": 9},
  {"n": 387, "en": "warranty", "ja": "保証", "ex": "The warranty lasts one year.", "exJa": "保証は1年です", "cat": 9},
  {"n": 388, "en": "disclaimer", "ja": "免責事項", "ex": "Read the disclaimer.", "exJa": "免責事項をお読みください", "cat": 9},
  {"n": 389, "en": "termination", "ja": "契約の終了・解除", "ex": "Termination requires thirty days' notice.", "exJa": "解除には30日前の通知が必要です", "cat": 9},
  {"n": 390, "en": "breach", "ja": "違反", "ex": "That is a breach of contract.", "exJa": "それは契約違反です", "cat": 9},
  {"n": 391, "en": "penalty", "ja": "違約金", "ex": "A penalty will apply.", "exJa": "違約金が発生します", "cat": 9},
  {"n": 392, "en": "negotiable", "ja": "交渉の余地がある", "ex": "The price is negotiable.", "exJa": "価格は相談可能です", "cat": 9},
  {"n": 393, "en": "purchase order", "ja": "発注書", "ex": "Send the purchase order today.", "exJa": "本日発注書を送ってください", "cat": 9},
  {"n": 394, "en": "order confirmation", "ja": "注文請書", "ex": "We received the order confirmation.", "exJa": "注文請書を受け取りました", "cat": 9},
  {"n": 395, "en": "procurement", "ja": "調達", "ex": "Procurement approved the deal.", "exJa": "購買部が承認しました", "cat": 9},
  {"n": 396, "en": "sourcing", "ja": "調達先の選定", "ex": "Sourcing takes two months.", "exJa": "調達先の選定に2か月かかります", "cat": 9},
  {"n": 397, "en": "lead time", "ja": "発注から納入までの期間", "ex": "The lead time is twelve weeks.", "exJa": "納期は12週間です", "cat": 9},
  {"n": 398, "en": "delivery date", "ja": "納期", "ex": "Can you move the delivery date?", "exJa": "納期を早められますか", "cat": 9},
  {"n": 399, "en": "shipment", "ja": "出荷", "ex": "The shipment left yesterday.", "exJa": "昨日出荷されました", "cat": 9},
  {"n": 400, "en": "freight", "ja": "貨物、運賃", "ex": "Freight costs increased.", "exJa": "運賃が上がりました", "cat": 9},
  {"n": 401, "en": "logistics", "ja": "物流", "ex": "Logistics is the hard part.", "exJa": "物流が難しい部分です", "cat": 9},
  {"n": 402, "en": "warehouse", "ja": "倉庫", "ex": "It is still in the warehouse.", "exJa": "まだ倉庫にあります", "cat": 9},
  {"n": 403, "en": "inventory", "ja": "在庫", "ex": "We have enough inventory.", "exJa": "在庫は十分あります", "cat": 9},
  {"n": 404, "en": "stock level", "ja": "在庫水準", "ex": "Check the stock level.", "exJa": "在庫水準を確認してください", "cat": 9},
  {"n": 405, "en": "shortage", "ja": "不足", "ex": "There is a chip shortage.", "exJa": "半導体が不足しています", "cat": 9},
  {"n": 406, "en": "surplus", "ja": "余剰", "ex": "We have surplus stock.", "exJa": "余剰在庫があります", "cat": 9},
  {"n": 407, "en": "backorder", "ja": "入荷待ちの注文", "ex": "The item is on backorder.", "exJa": "その品は入荷待ちです", "cat": 9},
  {"n": 408, "en": "supply chain", "ja": "供給網", "ex": "The supply chain is stable.", "exJa": "供給網は安定しています", "cat": 9},
  {"n": 409, "en": "customs clearance", "ja": "通関手続き", "ex": "Customs clearance took three days.", "exJa": "通関に3日かかりました", "cat": 9},
  {"n": 410, "en": "tariff", "ja": "関税", "ex": "Tariffs raised the price.", "exJa": "関税で価格が上がりました", "cat": 9},
  {"n": 411, "en": "import", "ja": "輸入", "ex": "We import from Taiwan.", "exJa": "台湾から輸入しています", "cat": 9},
  {"n": 412, "en": "export", "ja": "輸出", "ex": "Export rules are strict.", "exJa": "輸出規制は厳しいです", "cat": 9},
  {"n": 413, "en": "defective", "ja": "不良のある", "ex": "Two units were defective.", "exJa": "2台が不良でした", "cat": 9},
  {"n": 414, "en": "return", "ja": "返品", "ex": "We accepted the return.", "exJa": "返品を受け付けました", "cat": 9},
  {"n": 415, "en": "replacement", "ja": "代替品", "ex": "We sent a replacement.", "exJa": "代替品を送りました", "cat": 9},
  {"n": 416, "en": "assess", "ja": "見極める、査定する", "ex": "Let's assess the risk.", "exJa": "リスクを見極めましょう", "cat": 10},
  {"n": 417, "en": "analyze", "ja": "分析する", "ex": "I analyzed the data.", "exJa": "データを分析しました", "cat": 10},
  {"n": 418, "en": "examine", "ja": "精査する", "ex": "We examined the report.", "exJa": "報告書を精査しました", "cat": 10},
  {"n": 419, "en": "identify", "ja": "特定する", "ex": "Identify the cause first.", "exJa": "まず原因を特定してください", "cat": 10},
  {"n": 420, "en": "determine", "ja": "見極めて決める", "ex": "We must determine the price.", "exJa": "価格を決める必要があります", "cat": 10},
  {"n": 421, "en": "specify", "ja": "明示する", "ex": "Please specify the model.", "exJa": "機種を明示してください", "cat": 10},
  {"n": 422, "en": "define", "ja": "定義する", "ex": "Define the scope clearly.", "exJa": "範囲を明確に定義してください", "cat": 10},
  {"n": 423, "en": "propose", "ja": "提案する", "ex": "I propose a shorter plan.", "exJa": "短縮案を提案します", "cat": 10},
  {"n": 424, "en": "recommend", "ja": "推奨する", "ex": "I recommend option B.", "exJa": "案Bを推奨します", "cat": 10},
  {"n": 425, "en": "suggest", "ja": "それとなく提案する", "ex": "May I suggest an alternative?", "exJa": "代案を出してもよいですか", "cat": 10},
  {"n": 426, "en": "consider", "ja": "検討する", "ex": "We will consider it.", "exJa": "検討します", "cat": 10},
  {"n": 427, "en": "review", "ja": "見直す", "ex": "Please review the draft.", "exJa": "草案を見直してください", "cat": 10},
  {"n": 428, "en": "revise", "ja": "手を入れて直す", "ex": "I revised the numbers.", "exJa": "数字を修正しました", "cat": 10},
  {"n": 429, "en": "adjust", "ja": "微調整する", "ex": "Adjust the schedule slightly.", "exJa": "日程を少し調整してください", "cat": 10},
  {"n": 430, "en": "modify", "ja": "変更を加える", "ex": "We modified the design.", "exJa": "設計を変更しました", "cat": 10},
  {"n": 431, "en": "update", "ja": "最新の状態にする", "ex": "Update the file, please.", "exJa": "ファイルを更新してください", "cat": 10},
  {"n": 432, "en": "replace", "ja": "置き換える", "ex": "Replace the old part.", "exJa": "古い部品を交換してください", "cat": 10},
  {"n": 433, "en": "improve", "ja": "改善する", "ex": "We improved the process.", "exJa": "工程を改善しました", "cat": 10},
  {"n": 434, "en": "enhance", "ja": "さらに高める", "ex": "This will enhance safety.", "exJa": "これで安全性が高まります", "cat": 10},
  {"n": 435, "en": "expand", "ja": "拡大する", "ex": "We plan to expand in Asia.", "exJa": "アジアで拡大する予定です", "cat": 10},
  {"n": 436, "en": "reduce", "ja": "減らす", "ex": "Reduce the cost by ten percent.", "exJa": "原価を10%下げてください", "cat": 10},
  {"n": 437, "en": "maintain", "ja": "維持する", "ex": "Maintain the current quality.", "exJa": "今の品質を維持してください", "cat": 10},
  {"n": 438, "en": "ensure", "ja": "確実にする", "ex": "Ensure the data is correct.", "exJa": "データが正しいことを確認してください", "cat": 10},
  {"n": 439, "en": "verify", "ja": "事実か検証する", "ex": "Verify the results.", "exJa": "結果を検証してください", "cat": 10},
  {"n": 440, "en": "validate", "ja": "妥当だと確認する", "ex": "We validated the model.", "exJa": "モデルの妥当性を確認しました", "cat": 10},
  {"n": 441, "en": "monitor", "ja": "継続的に見守る", "ex": "Monitor the system daily.", "exJa": "毎日システムを監視してください", "cat": 10},
  {"n": 442, "en": "track", "ja": "追跡する", "ex": "Track the shipment online.", "exJa": "出荷状況を追跡してください", "cat": 10},
  {"n": 443, "en": "measure", "ja": "測る", "ex": "Measure the impact.", "exJa": "影響を測ってください", "cat": 10},
  {"n": 444, "en": "report", "ja": "報告する", "ex": "Report it to your manager.", "exJa": "上司に報告してください", "cat": 10},
  {"n": 445, "en": "submit", "ja": "提出する", "ex": "Submit the form by Friday.", "exJa": "金曜までに提出してください", "cat": 10},
  {"n": 446, "en": "compile", "ja": "取りまとめる", "ex": "I compiled the responses.", "exJa": "回答を取りまとめました", "cat": 10},
  {"n": 447, "en": "process", "ja": "処理する", "ex": "We process orders daily.", "exJa": "注文を毎日処理しています", "cat": 10},
  {"n": 448, "en": "handle", "ja": "対応する", "ex": "She handles overseas clients.", "exJa": "彼女が海外顧客を担当します", "cat": 10},
  {"n": 449, "en": "arrange", "ja": "手配する", "ex": "I'll arrange a meeting.", "exJa": "打ち合わせを手配します", "cat": 10},
  {"n": 450, "en": "facilitate", "ja": "円滑に進める", "ex": "He facilitated the discussion.", "exJa": "彼が議論を進行しました", "cat": 10},
  {"n": 451, "en": "persuade", "ja": "説得する", "ex": "We persuaded the client.", "exJa": "顧客を説得しました", "cat": 10},
  {"n": 452, "en": "convince", "ja": "納得させる", "ex": "The data convinced them.", "exJa": "データが彼らを納得させました", "cat": 10},
  {"n": 453, "en": "justify", "ja": "妥当だと示す", "ex": "Justify the extra cost.", "exJa": "追加費用の妥当性を示してください", "cat": 10},
  {"n": 454, "en": "demonstrate", "ja": "実際に示す", "ex": "Demonstrate the value clearly.", "exJa": "価値を明確に示してください", "cat": 10},
  {"n": 455, "en": "illustrate", "ja": "例で分かりやすく示す", "ex": "Let me illustrate with an example.", "exJa": "例を挙げて説明します", "cat": 10},
  {"n": 456, "en": "indicate", "ja": "示す", "ex": "The data indicates growth.", "exJa": "データは成長を示しています", "cat": 10},
  {"n": 457, "en": "imply", "ja": "暗に含む", "ex": "That reply implies a delay.", "exJa": "その返事は遅れを示唆しています", "cat": 10},
  {"n": 458, "en": "assume", "ja": "前提として考える", "ex": "Don't assume they agree.", "exJa": "同意していると決めつけないでください", "cat": 10},
  {"n": 459, "en": "anticipate", "ja": "先読みする", "ex": "We anticipate strong demand.", "exJa": "強い需要を見込んでいます", "cat": 10},
  {"n": 460, "en": "prioritize", "ja": "優先順位をつける", "ex": "Prioritize the top three.", "exJa": "上位3件を優先してください", "cat": 10},
  {"n": 461, "en": "assign", "ja": "割り当てる", "ex": "Assign this to Sato.", "exJa": "これを佐藤さんに割り当ててください", "cat": 10},
  {"n": 462, "en": "authorize", "ja": "権限を与える", "ex": "Only managers can authorize this.", "exJa": "管理職のみ承認できます", "cat": 10},
  {"n": 463, "en": "approve", "ja": "承認する", "ex": "The budget was approved.", "exJa": "予算が承認されました", "cat": 10},
  {"n": 464, "en": "decline", "ja": "丁重に断る", "ex": "We declined the offer.", "exJa": "提案を辞退しました", "cat": 10},
  {"n": 465, "en": "withdraw", "ja": "取り下げる", "ex": "They withdrew the proposal.", "exJa": "提案を取り下げました", "cat": 10},
  {"n": 466, "en": "feasible", "ja": "実現可能な", "ex": "Is this schedule feasible?", "exJa": "この日程は実現可能ですか", "cat": 11},
  {"n": 467, "en": "viable", "ja": "成り立つ、現実的な", "ex": "It is not a viable option.", "exJa": "現実的な選択肢ではありません", "cat": 11},
  {"n": 468, "en": "reasonable", "ja": "妥当な", "ex": "The price is reasonable.", "exJa": "価格は妥当です", "cat": 11},
  {"n": 469, "en": "significant", "ja": "無視できないほど大きい", "ex": "There is a significant delay.", "exJa": "無視できない遅れがあります", "cat": 11},
  {"n": 470, "en": "substantial", "ja": "かなりの", "ex": "We made substantial progress.", "exJa": "かなりの進展がありました", "cat": 11},
  {"n": 471, "en": "minimal", "ja": "最小限の", "ex": "The impact was minimal.", "exJa": "影響は最小限でした", "cat": 11},
  {"n": 472, "en": "sufficient", "ja": "十分な", "ex": "We have sufficient stock.", "exJa": "在庫は十分です", "cat": 11},
  {"n": 473, "en": "adequate", "ja": "必要を満たす、適切な", "ex": "The support was adequate.", "exJa": "支援は十分なものでした", "cat": 11},
  {"n": 474, "en": "relevant", "ja": "関連のある", "ex": "Send only relevant data.", "exJa": "関連するデータだけ送ってください", "cat": 11},
  {"n": 475, "en": "applicable", "ja": "当てはまる", "ex": "This rule is not applicable.", "exJa": "この規則は当てはまりません", "cat": 11},
  {"n": 476, "en": "preliminary", "ja": "予備的な、初期段階の", "ex": "These are preliminary results.", "exJa": "これは暫定の結果です", "cat": 11},
  {"n": 477, "en": "comprehensive", "ja": "網羅的な", "ex": "We need a comprehensive review.", "exJa": "網羅的な見直しが必要です", "cat": 11},
  {"n": 478, "en": "consistent", "ja": "一貫した", "ex": "Keep the format consistent.", "exJa": "書式を統一してください", "cat": 11},
  {"n": 479, "en": "flexible", "ja": "融通のきく", "ex": "Our schedule is flexible.", "exJa": "日程は柔軟に対応できます", "cat": 11},
  {"n": 480, "en": "stable", "ja": "安定した", "ex": "Supply is stable now.", "exJa": "供給は今は安定しています", "cat": 11},
  {"n": 481, "en": "critical", "ja": "決定的に重要な", "ex": "Timing is critical here.", "exJa": "ここでは時期が決定的です", "cat": 11},
  {"n": 482, "en": "potential", "ja": "潜在的な", "ex": "There is potential demand.", "exJa": "潜在的な需要があります", "cat": 11},
  {"n": 483, "en": "existing", "ja": "既存の", "ex": "We use the existing system.", "exJa": "既存システムを使います", "cat": 11},
  {"n": 484, "en": "additional", "ja": "追加の", "ex": "There is no additional cost.", "exJa": "追加費用はありません", "cat": 11},
  {"n": 485, "en": "alternative", "ja": "代わりとなる", "ex": "Do you have an alternative plan?", "exJa": "代案はありますか", "cat": 11},
  {"n": 486, "en": "respective", "ja": "それぞれの", "ex": "Send it to the respective teams.", "exJa": "それぞれのチームに送ってください", "cat": 11},
  {"n": 487, "en": "mutual", "ja": "相互の", "ex": "It is a mutual benefit.", "exJa": "相互の利益です", "cat": 11},
  {"n": 488, "en": "accordingly", "ja": "それに応じて", "ex": "Plan accordingly.", "exJa": "それに応じて計画してください", "cat": 11},
  {"n": 489, "en": "consequently", "ja": "その結果として", "ex": "Consequently, we lost the deal.", "exJa": "その結果、失注しました", "cat": 11},
  {"n": 490, "en": "therefore", "ja": "したがって", "ex": "Therefore, we need more time.", "exJa": "したがって、もっと時間が必要です", "cat": 11},
  {"n": 491, "en": "however", "ja": "しかしながら", "ex": "However, the cost is high.", "exJa": "しかし、費用が高いです", "cat": 11},
  {"n": 492, "en": "nevertheless", "ja": "それでもなお", "ex": "Nevertheless, we will try.", "exJa": "それでも挑戦します", "cat": 11},
  {"n": 493, "en": "whereas", "ja": "〜である一方で", "ex": "Sales rose, whereas profit fell.", "exJa": "売上は伸びた一方、利益は落ちました", "cat": 11},
  {"n": 494, "en": "regarding", "ja": "〜に関して", "ex": "Regarding the price, I agree.", "exJa": "価格については同意します", "cat": 11},
  {"n": 495, "en": "in terms of", "ja": "〜の観点では", "ex": "In terms of cost, it works.", "exJa": "費用の観点では成立します", "cat": 11},
  {"n": 496, "en": "due to", "ja": "〜が原因で", "ex": "The delay is due to weather.", "exJa": "遅れは天候が原因です", "cat": 11},
  {"n": 497, "en": "in addition", "ja": "加えて", "ex": "In addition, we offer support.", "exJa": "加えて、支援も提供します", "cat": 11},
  {"n": 498, "en": "furthermore", "ja": "さらに", "ex": "Furthermore, demand is rising.", "exJa": "さらに需要も伸びています", "cat": 11},
  {"n": 499, "en": "on the other hand", "ja": "他方で", "ex": "On the other hand, risk increases.", "exJa": "他方でリスクは増えます", "cat": 11},
  {"n": 500, "en": "as a result", "ja": "結果として", "ex": "As a result, sales doubled.", "exJa": "結果として売上が倍になりました", "cat": 11},
];
